### Root ###
GET http://92.255.109.118:5000/ HTTP/1.1

### Get users ###
GET http://92.255.109.118:5000/api/users HTTP/1.1

### Registration ###
POST http://92.255.109.118:5000/api/registration HTTP/1.1
Content-Type:  application/json

{
	"email": "orangecube.team@ya.ru",
	"password": "12345"
}

### Login ###
POST http://92.255.109.118:5000/api/login HTTP/1.1
Content-Type:  application/json

{
	"email": "orangecube.team@ya.ru",
	"password": "12345"
}

### Logout ###
POST http://92.255.109.118:5000/api/logout HTTP/1.1
Content-Type:  application/json

{
	"email": "orangecube.team@ya.ru",
	"password": "12345"
}

### Get All Users ###
GET http://92.255.109.118:5000/api/users HTTP/1.1


### Ya.ru ###
GET http://ya.ru HTTP/1.1
